### ISSUE TITLE
Could not log in

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/vectorpea#20] opened 2023-10-25 03:02 UTC
![image](https://github.com/photopea/vectorpea/assets/11801254/39945c0d-3d42-4865-aa13-03d8e4bf107c)

After trying to log in with google account i get this message.

And i don't log in

**Comment by photopea** [comment] 2023-10-26 09:14
Could you tell me what should I do to see it myself?

**Comment by photopea** [comment] 2023-11-23 16:12
I have to close it because of lack of details :(

**Closed by photopea** 2023-11-23 16:12 UTC

**Comment by TheRadicalDreamer** [comment] 2023-11-23 22:10
[Screen recording 2023-11-23 19.09.54.webm](https://github.com/photopea/vectorpea/assets/11801254/e2861702-d9b8-4603-ba07-7c90775535a5)
here is a video

**Comment by photopea** [comment] 2023-11-24 10:50
You never mentioned, that you are doing it in the Installed version, and that you use Chrome OS.

I still can not reproduce it in Chrome on Windows. When I click "Log in" in the installed version, it opens the other website in a regular browser (not in the installed version as in your case), and I can log in.

I think it is a bug in Chrome OS. You can report it to them. Or simply log in at www.vectorpea.com in your web browser, and you should stay logged in in the installed app.

**Comment by TheRadicalDreamer** [comment] 2023-11-26 19:19
Yes, when i opened in the tab browser i could log in.

I'll report this.

Thanks!

**Comment by burnsboyamazing** [comment] 2024-02-14 17:29
It fixed issues logging the account in with Google @TheRadicalDreamer.
[Screen recording 2024-02-14 12.27.36.webm](https://github.com/photopea/vectorpea/assets/154830140/19a300b1-ba74-455f-855e-483d84e93f12)

**Comment by Alexander-Burns** [comment] 2024-04-24 18:08
@TheRadicalDreamer See video of the same issue but Error 400: admin_policy_enforced in Google, also the screenshot.
![Screenshot 2024-04-24 14 07 03](https://github.com/photopea/vectorpea/assets/113866683/2c335d26-defe-45a7-86fb-d5c2d50a84b7)
[Screen recording 2024-04-24 14.06.31.webm](https://github.com/photopea/vectorpea/assets/113866683/b7e42b22-e39f-4a71-866d-c173f0e0f632)
